#!/usr/bin/expect

# Use this script to send ssh keys to the server without being prompted
# for a password

if {[llength $argv] != 3} {
    send_user "Usage: set-key <user> <server> <password>\n"
    exit 1
}

set user [lindex $argv 0]
set server [lindex $argv 1]
set pw [lindex $argv 2]

spawn ssh-copy-id $user@$server
expect "assword"
send "$pw\r"
interact