site_name: git-keeper Documentation
repo_url: https://github.com/git-keeper/git-keeper
nav:
    - Home: index.md
    - 'Faculty Users': faculty-users.md
    - 'Admin Users': admin-users.md
    - Reference: reference.md
    - Developers: developers.md
theme: readthedocs
markdown_extensions:
    - admonition
    - toc
