
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.provision "shell", inline:<<-SCRIPT
        useradd -ms /bin/bash keeper
        usermod -aG keeper keeper
        usermod -aG vagrant keeper
        echo 'keeper ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
        echo 'keeper:keeper' | chpasswd
        apt-get update && apt-get install -y python3-pip libssl-dev
        apt-get clean
        sudo -H pip3 install -U pip setuptools
        pip3 install cryptography
    SCRIPT
    config.vm.provision "file", source:"../ssh_keys", destination:"/home/vagrant/ssh_keys"
    config.vm.provision "shell", inline:<<-SCRIPT
        mkdir -p /home/keeper/.ssh
        chmod 700 /home/keeper/.ssh
        cp '/home/vagrant/ssh_keys/keeper_rsa.pub' '/home/keeper/.ssh/authorized_keys'
        chown -R keeper /home/keeper/.ssh
        chgrp -R keeper /home/keeper/.ssh
        chmod -R 600 /home/keeper/.ssh/*
    SCRIPT
end
