
# This file defines two vagrant VMs, one for the git-keeper server (gkserver), and one to host faculty
# and student accounts (gkclient).
#
# The base gkserver image is configured as described in the server setup document (github wiki).
#
# The base gkclient image has four users, `prof`, `prof2`, `student`, and `student2`.
#
# On both systems, ssh keys are in place for password-less logins.  The folder `ssh_provision` contains
# `keeper_rsa`, `prof_rsa`, etc. for each user.  If required, each usuer's password is their username
# (e.g. keeper:keeper, prof:prof, etc.)
#
# This file configures the two VMs to facilitate testing:
# * During provisioning, `git-keeper-core` and `git-keeper-server` are installed on the `gkserver`.  Similarly,
#   `git-keeper-core` and `git-keeper-client` are installed on `gkclient`.
# * During provisioning, a mock email server launches.  Instead of sending email, it writes email individual
#   files in /email.  Each file is named with the recipient username and a number.
Vagrant.configure("2") do |config|

    config.vm.define "gkserver" do |gkserver|
        # FIXME upload to vagrant cloud and point to that version
        gkserver.vm.box = "gkserver"
        gkserver.vm.hostname = "gkserver"
        gkserver.vm.network "private_network", ip:"20.0.1.100"

        gkserver.vm.synced_folder "../../git-keeper-core", "/git-keeper-core"
        gkserver.vm.synced_folder "../../git-keeper-server", "/git-keeper-server"

        gkserver.vm.provision "shell", inline:<<-SCRIPT
            pip3 install /git-keeper-core
            pip3 install /git-keeper-server
            python3 /email/mysmtpd.py 25 /email &
        SCRIPT
    end

    config.vm.define "gkclient" do |gkclient|
        # FIXME upload to vagrant cloud and point to that version
        gkclient.vm.box = "gkclient"
        gkclient.vm.network "private_network", ip:"20.0.1.200"
        gkclient.vm.provision "shell", inline:"sed -i '$ a 20.0.1.100 gkserver' /etc/hosts"
    end
end