# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.provision "shell", path: "server_provision.sh"
  config.vm.network :forwarded_port, guest: 22, host: 12914, id: 'ssh'
end

