#!/usr/bin/expect

# This is called from the connect script, and is not intended to be called directly.

if {[llength $argv] != 4} {
    send_user "Usage: connect <hostname> <port> <username> <password>\n"
    exit 1
}

set host [lindex $argv 0]
set port [lindex $argv 1]
set user [lindex $argv 2]
set pass [lindex $argv 3]

# The port changes each time you connect, which can cause your known_hosts file to
# grow rapidly if you re-run/re-connect frequently.  To avoid this we turn off
# checking (so it doesn't prompt you about a new host) and send the known_host
# write to /dev/null.
spawn ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $user@$host -p $port
expect "assword"
send "$pass\r"
interact
