#!/bin/bash

# This is a convenience script to connect to a running server running through
# docker.  The docker daemon will forward a connect to the container's port 22
# when you connect to the docker daemon IP on a mapped port.
#
# This script uses docker commands to look up the ip of the docker deamon and the
# mapped port number.  These are passed to an expect script that connects as
# keeper with the password g1tk33p3r.

./helper.exp `docker-machine ip` `docker port git-keeper-client 22 | cut -c 9-` prof prof
